package ${package};

import cn.watsontech.snapagent.core.tool.ToolContext;
import cn.watsontech.snapagent.core.tool.ToolPluginAnnotation;
import cn.watsontech.snapagent.core.tool.ToolProvider;
import cn.watsontech.snapagent.core.tool.ToolResult;

import java.util.Map;

/**
 * ${displayName} - ${description}
 *
 * Generated by snap-agent-plugin-archetype. Replace the execute() body
 * with your plugin's actual logic.
 */
@ToolPluginAnnotation(
    id = "${pluginId}",
    toolType = "${toolType}",
    displayName = "${displayName}",
    description = "${description}",
    version = "1.0.0"
)
public class ${className} implements ToolProvider {

    @Override
    public String name() {
        return "${pluginId}";
    }

    @Override
    public String schema() {
        return "{\"name\":\"${toolType}\","
             + "\"description\":\"${description}\","
             + "\"input_schema\":{\"type\":\"object\","
             + "\"properties\":{\"query\":{\"type\":\"string\","
             + "\"description\":\"The query string to pass to the tool\"}},"
             + "\"required\":[\"query\"]}}";
    }

    @Override
    public ToolResult execute(Map<String, Object> args, ToolContext ctx) {
        long start = System.currentTimeMillis();
        try {
            String query = args != null ? (String) args.get("query") : null;
            if (query == null || query.isEmpty()) {
                return ToolResult.error("missing required parameter: query",
                                         System.currentTimeMillis() - start);
            }
            String content = "# ${displayName}\n\nQuery: " + query;
            return ToolResult.success(content, 1, System.currentTimeMillis() - start);
        } catch (RuntimeException e) {
            return ToolResult.error("${pluginId} failed: " + e.getMessage(),
                                     System.currentTimeMillis() - start);
        }
    }
}
