package cn.watsontech.snapagent.boot2x.skill;

import cn.watsontech.snapagent.core.skill.SkillRegistry;
import cn.watsontech.snapagent.core.skill.SkillTemplate;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import org.mockito.Mockito;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Collections;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.Mockito.when;

@DisplayName("SkillTemplateCatalog")
class SkillTemplateCatalogTest {

    @TempDir
    Path tempDir;

    private SkillRegistry skillRegistry;
    private SkillTemplateCatalog catalog;

    @BeforeEach
    void setUp() {
        skillRegistry = Mockito.mock(SkillRegistry.class);
        when(skillRegistry.all()).thenReturn(Collections.emptyList());
        catalog = new SkillTemplateCatalog(tempDir, skillRegistry);
    }

    @Test
    @DisplayName("listTemplates returns templates from catalog resource")
    void shouldListTemplates() {
        List<SkillTemplate> templates = catalog.listTemplates();
        // Catalog is loaded from classpath resource; if it exists, templates should not be empty
        // (The catalog JSON should have been generated by the build)
        assertThat(templates).isNotNull();
    }

    @Test
    @DisplayName("getTemplate returns null for unknown template")
    void shouldReturnNullForUnknownTemplate() {
        SkillTemplate t = catalog.getTemplate("nonexistent-skill");
        assertThat(t).isNull();
    }

    @Test
    @DisplayName("getCategories returns distinct sorted categories")
    void shouldReturnCategories() {
        List<String> categories = catalog.getCategories();
        assertThat(categories).isNotNull();
        // Should be sorted
        for (int i = 1; i < categories.size(); i++) {
            assertThat(categories.get(i).compareTo(categories.get(i - 1))).isGreaterThanOrEqualTo(0);
        }
    }

    @Test
    @DisplayName("install writes template content to upload directory")
    void shouldInstallTemplate() throws IOException {
        // Write a known template to the catalog resource path (not possible in test)
        // Instead, test that install returns false for non-existent template
        boolean result = catalog.install("nonexistent-skill");
        assertThat(result).isFalse();
    }

    @Test
    @DisplayName("uninstall returns false when template file doesn't exist")
    void shouldReturnFalseWhenUninstallingNonExistent() {
        boolean result = catalog.uninstall("nonexistent-skill");
        assertThat(result).isFalse();
    }

    @Test
    @DisplayName("uninstall removes template file from upload directory")
    void shouldUninstallTemplate() throws IOException {
        // Create a fake installed skill file
        Path skillFile = tempDir.resolve("test-skill.md");
        Files.write(skillFile, "# Test Skill".getBytes(StandardCharsets.UTF_8));
        assertThat(Files.exists(skillFile)).isTrue();

        // Uninstall should remove the file
        boolean result = catalog.uninstall("test-skill");
        assertThat(result).isTrue();
        assertThat(Files.exists(skillFile)).isFalse();
    }

    @Test
    @DisplayName("constructor rejects null uploadDir")
    void shouldRejectNullUploadDir() {
        assertThatThrownBy(() -> new SkillTemplateCatalog(null, skillRegistry))
                .isInstanceOf(IllegalArgumentException.class)
                .hasMessageContaining("uploadDir");
    }

    @Test
    @DisplayName("constructor rejects null skillRegistry")
    void shouldRejectNullSkillRegistry() {
        assertThatThrownBy(() -> new SkillTemplateCatalog(tempDir, null))
                .isInstanceOf(IllegalArgumentException.class)
                .hasMessageContaining("skillRegistry");
    }

    @Test
    @DisplayName("installed status reflects skill registry")
    void shouldReflectInstalledStatus() {
        // Templates from catalog should show installed=false when registry is empty
        List<SkillTemplate> templates = catalog.listTemplates();
        for (SkillTemplate t : templates) {
            assertThat(t.isInstalled()).isFalse();
        }
    }
}
