package cn.watsontech.snapagent.boot2x.tool;

import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * SQL safety guard — enforces read-only policy on SQL queries generated by the LLM.
 *
 * <p>This is the primary syntactic defence against prompt-injection-driven write
 * operations. It is <strong>not</strong> a semantic analyser; the secondary defence
 * is the read-only DB user granted to the agent's DataSource.</p>
 *
 * <p>Validation steps (per TDD_SPEC §UC-11 and design doc 04 §2.2):</p>
 * <ol>
 *   <li>Strip SQL comments (line, hash, block) and trim.</li>
 *   <li>Strip trailing semicolons.</li>
 *   <li>Reject multi-statement (if a {@code ;} remains after trailing trim).</li>
 *   <li>First-keyword whitelist: {@code WITH|SELECT|SHOW|DESCRIBE|EXPLAIN|DESC}.</li>
 *   <li>Dangerous-keyword blacklist (case-insensitive, across entire SQL).</li>
 *   <li>LIMIT injection: append {@code LIMIT {max}} when absent; rewrite when over max.</li>
 * </ol>
 */
public class SqlGuard {

    private static final Pattern FIRST_KEYWORD_WHITELIST = Pattern.compile(
            "^\\s*(WITH|SELECT|SHOW|DESCRIBE|EXPLAIN|DESC)\\b",
            Pattern.CASE_INSENSITIVE);

    private static final Pattern BLACKLIST = Pattern.compile(
            "\\b(INSERT|UPDATE|DELETE|DROP|CREATE|ALTER|TRUNCATE|RENAME|GRANT|REVOKE|"
                    + "REPLACE|MERGE|CALL|HANDLER|LOCK|UNLOCK|FLUSH|RESET|SHUTDOWN|KILL|"
                    + "LOAD|LOAD_FILE|INTO\\s+OUTFILE|INTO\\s+DUMPFILE|INTO\\s+@|SLEEP|BENCHMARK)\\b",
            Pattern.CASE_INSENSITIVE);

    private static final Pattern BLOCK_COMMENT = Pattern.compile("/\\*.*?\\*/", Pattern.DOTALL);
    private static final Pattern LINE_COMMENT = Pattern.compile("--.*$", Pattern.MULTILINE);
    private static final Pattern HASH_COMMENT = Pattern.compile("#.*$", Pattern.MULTILINE);

    /** MySQL alternative statement terminators \g and \G. */
    private static final Pattern MYSQL_TERMINATOR = Pattern.compile(
            "\\\\(g|G)\\s*$");

    /** LIMIT with optional two-arg syntax: LIMIT offset, count or LIMIT count OFFSET offset. */
    private static final Pattern LIMIT_PATTERN = Pattern.compile(
            "LIMIT\\s+(\\d+)\\s*(?:,\\s*(\\d+))?",
            Pattern.CASE_INSENSITIVE);

    private final int maxResultRows;

    public SqlGuard(int maxResultRows) {
        if (maxResultRows <= 0) {
            throw new IllegalArgumentException("maxResultRows must be positive");
        }
        this.maxResultRows = maxResultRows;
    }

    public int getMaxResultRows() {
        return maxResultRows;
    }

    /**
     * Validate and sanitise the given SQL.
     *
     * @param sql raw SQL from the LLM tool_use block
     * @return a {@link Result} with either the sanitised SQL (allowed) or a rejection reason
     */
    public Result validate(String sql) {
        if (sql == null || sql.trim().isEmpty()) {
            return Result.reject("SQL 被只读策略拒绝：SQL 为空");
        }

        // Step 1: strip comments
        String sanitized = stripComments(sql).trim();

        // Step 2: strip trailing semicolons and MySQL \g/\G terminators
        while (sanitized.endsWith(";")) {
            sanitized = sanitized.substring(0, sanitized.length() - 1).trim();
        }
        sanitized = MYSQL_TERMINATOR.matcher(sanitized).replaceAll("").trim();

        if (sanitized.isEmpty()) {
            return Result.reject("SQL 被只读策略拒绝：SQL 为空（仅注释）");
        }

        // Step 3: multi-statement rejection (semicolons or \g/\G in the middle)
        if (sanitized.contains(";") || sanitized.matches(".*\\\\[gG].*")) {
            return Result.reject("SQL 被只读策略拒绝：多语句（含分号或 \\g/\\G）");
        }

        // Step 4: first-keyword whitelist
        Matcher whitelistMatcher = FIRST_KEYWORD_WHITELIST.matcher(sanitized);
        if (!whitelistMatcher.find()) {
            String firstWord = extractFirstWord(sanitized);
            return Result.reject("SQL 被只读策略拒绝：首关键字 " + firstWord);
        }

        // Step 5: dangerous-keyword blacklist
        Matcher blacklistMatcher = BLACKLIST.matcher(sanitized);
        if (blacklistMatcher.find()) {
            String matched = blacklistMatcher.group(1).toUpperCase().replaceAll("\\s+", " ");
            return Result.reject("SQL 被只读策略拒绝：黑名单关键字 " + matched);
        }

        // Step 6: LIMIT injection / rewrite
        sanitized = injectOrRewriteLimit(sanitized);

        return Result.ok(sanitized);
    }

    private String stripComments(String sql) {
        String s = BLOCK_COMMENT.matcher(sql).replaceAll(" ");
        s = LINE_COMMENT.matcher(s).replaceAll(" ");
        s = HASH_COMMENT.matcher(s).replaceAll(" ");
        return s;
    }

    private String extractFirstWord(String sql) {
        String trimmed = sql.trim();
        int i = 0;
        while (i < trimmed.length() && !Character.isWhitespace(trimmed.charAt(i))) {
            i++;
        }
        return trimmed.substring(0, i).toUpperCase();
    }

    /** Keywords that support LIMIT clause in MySQL. */
    private static final Pattern LIMIT_SUPPORTED = Pattern.compile(
            "^\\s*(SELECT|WITH|EXPLAIN)\\b",
            Pattern.CASE_INSENSITIVE);

    private String injectOrRewriteLimit(String sql) {
        // SHOW, DESCRIBE, DESC don't support LIMIT in MySQL — skip injection
        if (!LIMIT_SUPPORTED.matcher(sql).find()) {
            return sql;
        }
        Matcher m = LIMIT_PATTERN.matcher(sql);
        if (m.find()) {
            // Two-arg LIMIT: LIMIT offset, count — the count is group(2) if present
            String countStr = m.group(2) != null ? m.group(2) : m.group(1);
            long limit = Long.parseLong(countStr);
            if (limit > maxResultRows) {
                if (m.group(2) != null) {
                    // Two-arg: rewrite count, keep offset
                    return m.replaceFirst("LIMIT " + m.group(1) + ", " + maxResultRows);
                }
                return m.replaceFirst("LIMIT " + maxResultRows);
            }
            return sql;
        }
        return sql + " LIMIT " + maxResultRows;
    }

    /** Immutable validation result. */
    public static final class Result {
        private final String sql;
        private final String reason;

        private Result(String sql, String reason) {
            this.sql = sql;
            this.reason = reason;
        }

        /** Allowed result with sanitised SQL. */
        public static Result ok(String sql) {
            return new Result(sql, null);
        }

        /** Rejected result with a human-readable reason. */
        public static Result reject(String reason) {
            return new Result(null, reason);
        }

        /** True when the SQL passed validation. */
        public boolean isAllowed() {
            return sql != null;
        }

        /** The sanitised SQL (only valid when {@link #isAllowed()} is true). */
        public String getSql() {
            return sql;
        }

        /** The rejection reason (only valid when {@link #isAllowed()} is false). */
        public String getReason() {
            return reason;
        }
    }
}
